export interface OpcodeItem {
  opcode: string;
  mnemonic: string;
  bytes: number;
  cycles: string;
  desc: string;
}

export const OPCODES_DATABASE: OpcodeItem[] = [
  // --- 00H to 3FH (59 valid opcodes) ---
  { opcode: "00", mnemonic: "NOP", bytes: 1, cycles: "4", desc: "No operation" },
  { opcode: "01", mnemonic: "LXI B, d16", bytes: 3, cycles: "10", desc: "Load immediate 16-bit data into Register Pair B-C" },
  { opcode: "02", mnemonic: "STAX B", bytes: 1, cycles: "7", desc: "Store Accumulator A into memory location pointed by BC" },
  { opcode: "03", mnemonic: "INX B", bytes: 1, cycles: "6", desc: "Increment Register Pair B-C by 1" },
  { opcode: "04", mnemonic: "INR B", bytes: 1, cycles: "4", desc: "Increment Register B by 1" },
  { opcode: "05", mnemonic: "DCR B", bytes: 1, cycles: "4", desc: "Decrement Register B by 1" },
  { opcode: "06", mnemonic: "MVI B, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Register B" },
  { opcode: "07", mnemonic: "RLC", bytes: 1, cycles: "4", desc: "Rotate Accumulator A left by 1 bit" },
  { opcode: "09", mnemonic: "DAD B", bytes: 1, cycles: "10", desc: "Add Register Pair B-C content to Register Pair H-L" },
  { opcode: "0A", mnemonic: "LDAX B", bytes: 1, cycles: "7", desc: "Load Accumulator A from memory location pointed by BC" },
  { opcode: "0B", mnemonic: "DCX B", bytes: 1, cycles: "6", desc: "Decrement Register Pair B-C by 1" },
  { opcode: "0C", mnemonic: "INR C", bytes: 1, cycles: "4", desc: "Increment Register C by 1" },
  { opcode: "0D", mnemonic: "DCR C", bytes: 1, cycles: "4", desc: "Decrement Register C by 1" },
  { opcode: "0E", mnemonic: "MVI C, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Register C" },
  { opcode: "0F", mnemonic: "RRC", bytes: 1, cycles: "4", desc: "Rotate Accumulator A right by 1 bit" },
  { opcode: "11", mnemonic: "LXI D, d16", bytes: 3, cycles: "10", desc: "Load immediate 16-bit data into Register Pair D-E" },
  { opcode: "12", mnemonic: "STAX D", bytes: 1, cycles: "7", desc: "Store Accumulator A into memory location pointed by DE" },
  { opcode: "13", mnemonic: "INX D", bytes: 1, cycles: "6", desc: "Increment Register Pair D-E by 1" },
  { opcode: "14", mnemonic: "INR D", bytes: 1, cycles: "4", desc: "Increment Register D by 1" },
  { opcode: "15", mnemonic: "DCR D", bytes: 1, cycles: "4", desc: "Decrement Register D by 1" },
  { opcode: "16", mnemonic: "MVI D, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Register D" },
  { opcode: "17", mnemonic: "RAL", bytes: 1, cycles: "4", desc: "Rotate Accumulator A left through Carry" },
  { opcode: "19", mnemonic: "DAD D", bytes: 1, cycles: "10", desc: "Add Register Pair D-E content to Register Pair H-L" },
  { opcode: "1A", mnemonic: "LDAX D", bytes: 1, cycles: "7", desc: "Load Accumulator A from memory location pointed by DE" },
  { opcode: "1B", mnemonic: "DCX D", bytes: 1, cycles: "6", desc: "Decrement Register Pair D-E by 1" },
  { opcode: "1C", mnemonic: "INR E", bytes: 1, cycles: "4", desc: "Increment Register E by 1" },
  { opcode: "1D", mnemonic: "DCR E", bytes: 1, cycles: "4", desc: "Decrement Register E by 1" },
  { opcode: "1E", mnemonic: "MVI E, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Register E" },
  { opcode: "1F", mnemonic: "RAR", bytes: 1, cycles: "4", desc: "Rotate Accumulator A right through Carry" },
  { opcode: "20", mnemonic: "RIM", bytes: 1, cycles: "4", desc: "Read Interrupt Mask into Accumulator A" },
  { opcode: "21", mnemonic: "LXI H, d16", bytes: 3, cycles: "10", desc: "Load immediate 16-bit data into Register Pair H-L" },
  { opcode: "22", mnemonic: "SHLD addr", bytes: 3, cycles: "16", desc: "Store Register Pair H-L directly to 16-bit memory address" },
  { opcode: "23", mnemonic: "INX H", bytes: 1, cycles: "6", desc: "Increment Register Pair H-L by 1" },
  { opcode: "24", mnemonic: "INR H", bytes: 1, cycles: "4", desc: "Increment Register H by 1" },
  { opcode: "25", mnemonic: "DCR H", bytes: 1, cycles: "4", desc: "Decrement Register H by 1" },
  { opcode: "26", mnemonic: "MVI H, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Register H" },
  { opcode: "27", mnemonic: "DAA", bytes: 1, cycles: "4", desc: "Decimal Adjust Accumulator A after BCD addition" },
  { opcode: "29", mnemonic: "DAD H", bytes: 1, cycles: "10", desc: "Add Register Pair H-L content to Register Pair H-L" },
  { opcode: "2A", mnemonic: "LHLD addr", bytes: 3, cycles: "16", desc: "Load Register Pair H-L directly from 16-bit memory address" },
  { opcode: "2B", mnemonic: "DCX H", bytes: 1, cycles: "6", desc: "Decrement Register Pair H-L by 1" },
  { opcode: "2C", mnemonic: "INR L", bytes: 1, cycles: "4", desc: "Increment Register L by 1" },
  { opcode: "2D", mnemonic: "DCR L", bytes: 1, cycles: "4", desc: "Decrement Register L by 1" },
  { opcode: "2E", mnemonic: "MVI L, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Register L" },
  { opcode: "2F", mnemonic: "CMA", bytes: 1, cycles: "4", desc: "Complement Accumulator A (one's complement)" },
  { opcode: "30", mnemonic: "SIM", bytes: 1, cycles: "4", desc: "Set Interrupt Mask using Accumulator A" },
  { opcode: "31", mnemonic: "LXI SP, d16", bytes: 3, cycles: "10", desc: "Load immediate 16-bit data into Stack Pointer" },
  { opcode: "32", mnemonic: "STA addr", bytes: 3, cycles: "13", desc: "Store Accumulator A directly to 16-bit memory address" },
  { opcode: "33", mnemonic: "INX SP", bytes: 1, cycles: "6", desc: "Increment Stack Pointer by 1" },
  { opcode: "34", mnemonic: "INR M", bytes: 1, cycles: "10", desc: "Increment memory pointed by HL by 1" },
  { opcode: "35", mnemonic: "DCR M", bytes: 1, cycles: "10", desc: "Decrement memory pointed by HL by 1" },
  { opcode: "36", mnemonic: "MVI M, d8", bytes: 2, cycles: "10", desc: "Move immediate 8-bit data to memory pointed by HL" },
  { opcode: "37", mnemonic: "STC", bytes: 1, cycles: "4", desc: "Set Carry Flag (CY = 1)" },
  { opcode: "39", mnemonic: "DAD SP", bytes: 1, cycles: "10", desc: "Add Stack Pointer content to Register Pair H-L" },
  { opcode: "3A", mnemonic: "LDA addr", bytes: 3, cycles: "13", desc: "Load Accumulator A directly from 16-bit memory address" },
  { opcode: "3B", mnemonic: "DCX SP", bytes: 1, cycles: "6", desc: "Decrement Stack Pointer by 1" },
  { opcode: "3C", mnemonic: "INR A", bytes: 1, cycles: "4", desc: "Increment Accumulator A by 1" },
  { opcode: "3D", mnemonic: "DCR A", bytes: 1, cycles: "4", desc: "Decrement Accumulator A by 1" },
  { opcode: "3E", mnemonic: "MVI A, d8", bytes: 2, cycles: "7", desc: "Move immediate 8-bit data to Accumulator A" },
  { opcode: "3F", mnemonic: "CMC", bytes: 1, cycles: "4", desc: "Complement Carry Flag" },

  // --- 40H to 7FH (MOV group + HLT: 64 valid opcodes) ---
  { opcode: "40", mnemonic: "MOV B, B", bytes: 1, cycles: "4", desc: "Move Register B to Register B" },
  { opcode: "41", mnemonic: "MOV B, C", bytes: 1, cycles: "4", desc: "Move Register C to Register B" },
  { opcode: "42", mnemonic: "MOV B, D", bytes: 1, cycles: "4", desc: "Move Register D to Register B" },
  { opcode: "43", mnemonic: "MOV B, E", bytes: 1, cycles: "4", desc: "Move Register E to Register B" },
  { opcode: "44", mnemonic: "MOV B, H", bytes: 1, cycles: "4", desc: "Move Register H to Register B" },
  { opcode: "45", mnemonic: "MOV B, L", bytes: 1, cycles: "4", desc: "Move Register L to Register B" },
  { opcode: "46", mnemonic: "MOV B, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Register B" },
  { opcode: "47", mnemonic: "MOV B, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Register B" },
  { opcode: "48", mnemonic: "MOV C, B", bytes: 1, cycles: "4", desc: "Move Register B to Register C" },
  { opcode: "49", mnemonic: "MOV C, C", bytes: 1, cycles: "4", desc: "Move Register C to Register C" },
  { opcode: "4A", mnemonic: "MOV C, D", bytes: 1, cycles: "4", desc: "Move Register D to Register C" },
  { opcode: "4B", mnemonic: "MOV C, E", bytes: 1, cycles: "4", desc: "Move Register E to Register C" },
  { opcode: "4C", mnemonic: "MOV C, H", bytes: 1, cycles: "4", desc: "Move Register H to Register C" },
  { opcode: "4D", mnemonic: "MOV C, L", bytes: 1, cycles: "4", desc: "Move Register L to Register C" },
  { opcode: "4E", mnemonic: "MOV C, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Register C" },
  { opcode: "4F", mnemonic: "MOV C, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Register C" },
  { opcode: "50", mnemonic: "MOV D, B", bytes: 1, cycles: "4", desc: "Move Register B to Register D" },
  { opcode: "51", mnemonic: "MOV D, C", bytes: 1, cycles: "4", desc: "Move Register C to Register D" },
  { opcode: "52", mnemonic: "MOV D, D", bytes: 1, cycles: "4", desc: "Move Register D to Register D" },
  { opcode: "53", mnemonic: "MOV D, E", bytes: 1, cycles: "4", desc: "Move Register E to Register D" },
  { opcode: "54", mnemonic: "MOV D, H", bytes: 1, cycles: "4", desc: "Move Register H to Register D" },
  { opcode: "55", mnemonic: "MOV D, L", bytes: 1, cycles: "4", desc: "Move Register L to Register D" },
  { opcode: "56", mnemonic: "MOV D, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Register D" },
  { opcode: "57", mnemonic: "MOV D, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Register D" },
  { opcode: "58", mnemonic: "MOV E, B", bytes: 1, cycles: "4", desc: "Move Register B to Register E" },
  { opcode: "59", mnemonic: "MOV E, C", bytes: 1, cycles: "4", desc: "Move Register C to Register E" },
  { opcode: "5A", mnemonic: "MOV E, D", bytes: 1, cycles: "4", desc: "Move Register D to Register E" },
  { opcode: "5B", mnemonic: "MOV E, E", bytes: 1, cycles: "4", desc: "Move Register E to Register E" },
  { opcode: "5C", mnemonic: "MOV E, H", bytes: 1, cycles: "4", desc: "Move Register H to Register E" },
  { opcode: "5D", mnemonic: "MOV E, L", bytes: 1, cycles: "4", desc: "Move Register L to Register E" },
  { opcode: "5E", mnemonic: "MOV E, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Register E" },
  { opcode: "5F", mnemonic: "MOV E, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Register E" },
  { opcode: "60", mnemonic: "MOV H, B", bytes: 1, cycles: "4", desc: "Move Register B to Register H" },
  { opcode: "61", mnemonic: "MOV H, C", bytes: 1, cycles: "4", desc: "Move Register C to Register H" },
  { opcode: "62", mnemonic: "MOV H, D", bytes: 1, cycles: "4", desc: "Move Register D to Register H" },
  { opcode: "63", mnemonic: "MOV H, E", bytes: 1, cycles: "4", desc: "Move Register E to Register H" },
  { opcode: "64", mnemonic: "MOV H, H", bytes: 1, cycles: "4", desc: "Move Register H to Register H" },
  { opcode: "65", mnemonic: "MOV H, L", bytes: 1, cycles: "4", desc: "Move Register L to Register H" },
  { opcode: "66", mnemonic: "MOV H, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Register H" },
  { opcode: "67", mnemonic: "MOV H, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Register H" },
  { opcode: "68", mnemonic: "MOV L, B", bytes: 1, cycles: "4", desc: "Move Register B to Register L" },
  { opcode: "69", mnemonic: "MOV L, C", bytes: 1, cycles: "4", desc: "Move Register C to Register L" },
  { opcode: "6A", mnemonic: "MOV L, D", bytes: 1, cycles: "4", desc: "Move Register D to Register L" },
  { opcode: "6B", mnemonic: "MOV L, E", bytes: 1, cycles: "4", desc: "Move Register E to Register L" },
  { opcode: "6C", mnemonic: "MOV L, H", bytes: 1, cycles: "4", desc: "Move Register H to Register L" },
  { opcode: "6D", mnemonic: "MOV L, L", bytes: 1, cycles: "4", desc: "Move Register L to Register L" },
  { opcode: "6E", mnemonic: "MOV L, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Register L" },
  { opcode: "6F", mnemonic: "MOV L, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Register L" },
  { opcode: "70", mnemonic: "MOV M, B", bytes: 1, cycles: "7", desc: "Move Register B to memory pointed by HL" },
  { opcode: "71", mnemonic: "MOV M, C", bytes: 1, cycles: "7", desc: "Move Register C to memory pointed by HL" },
  { opcode: "72", mnemonic: "MOV M, D", bytes: 1, cycles: "7", desc: "Move Register D to memory pointed by HL" },
  { opcode: "73", mnemonic: "MOV M, E", bytes: 1, cycles: "7", desc: "Move Register E to memory pointed by HL" },
  { opcode: "74", mnemonic: "MOV M, H", bytes: 1, cycles: "7", desc: "Move Register H to memory pointed by HL" },
  { opcode: "75", mnemonic: "MOV M, L", bytes: 1, cycles: "7", desc: "Move Register L to memory pointed by HL" },
  { opcode: "76", mnemonic: "HLT", bytes: 1, cycles: "5", desc: "Halt CPU execution and put processor in standby" },
  { opcode: "77", mnemonic: "MOV M, A", bytes: 1, cycles: "7", desc: "Move Accumulator A to memory pointed by HL" },
  { opcode: "78", mnemonic: "MOV A, B", bytes: 1, cycles: "4", desc: "Move Register B to Accumulator A" },
  { opcode: "79", mnemonic: "MOV A, C", bytes: 1, cycles: "4", desc: "Move Register C to Accumulator A" },
  { opcode: "7A", mnemonic: "MOV A, D", bytes: 1, cycles: "4", desc: "Move Register D to Accumulator A" },
  { opcode: "7B", mnemonic: "MOV A, E", bytes: 1, cycles: "4", desc: "Move Register E to Accumulator A" },
  { opcode: "7C", mnemonic: "MOV A, H", bytes: 1, cycles: "4", desc: "Move Register H to Accumulator A" },
  { opcode: "7D", mnemonic: "MOV A, L", bytes: 1, cycles: "4", desc: "Move Register L to Accumulator A" },
  { opcode: "7E", mnemonic: "MOV A, M", bytes: 1, cycles: "7", desc: "Move memory pointed by HL to Accumulator A" },
  { opcode: "7F", mnemonic: "MOV A, A", bytes: 1, cycles: "4", desc: "Move Accumulator A to Accumulator A" },

  // --- 80H to BFH (ALU Register-to-A Group: 64 valid opcodes) ---
  { opcode: "80", mnemonic: "ADD B", bytes: 1, cycles: "4", desc: "Add Register B to Accumulator A" },
  { opcode: "81", mnemonic: "ADD C", bytes: 1, cycles: "4", desc: "Add Register C to Accumulator A" },
  { opcode: "82", mnemonic: "ADD D", bytes: 1, cycles: "4", desc: "Add Register D to Accumulator A" },
  { opcode: "83", mnemonic: "ADD E", bytes: 1, cycles: "4", desc: "Add Register E to Accumulator A" },
  { opcode: "84", mnemonic: "ADD H", bytes: 1, cycles: "4", desc: "Add Register H to Accumulator A" },
  { opcode: "85", mnemonic: "ADD L", bytes: 1, cycles: "4", desc: "Add Register L to Accumulator A" },
  { opcode: "86", mnemonic: "ADD M", bytes: 1, cycles: "7", desc: "Add memory pointed by HL to Accumulator A" },
  { opcode: "87", mnemonic: "ADD A", bytes: 1, cycles: "4", desc: "Add Accumulator A to Accumulator A" },
  { opcode: "88", mnemonic: "ADC B", bytes: 1, cycles: "4", desc: "Add Register B and Carry Flag to Accumulator A" },
  { opcode: "89", mnemonic: "ADC C", bytes: 1, cycles: "4", desc: "Add Register C and Carry Flag to Accumulator A" },
  { opcode: "8A", mnemonic: "ADC D", bytes: 1, cycles: "4", desc: "Add Register D and Carry Flag to Accumulator A" },
  { opcode: "8B", mnemonic: "ADC E", bytes: 1, cycles: "4", desc: "Add Register E and Carry Flag to Accumulator A" },
  { opcode: "8C", mnemonic: "ADC H", bytes: 1, cycles: "4", desc: "Add Register H and Carry Flag to Accumulator A" },
  { opcode: "8D", mnemonic: "ADC L", bytes: 1, cycles: "4", desc: "Add Register L and Carry Flag to Accumulator A" },
  { opcode: "8E", mnemonic: "ADC M", bytes: 1, cycles: "7", desc: "Add memory pointed by HL and Carry Flag to Accumulator A" },
  { opcode: "8F", mnemonic: "ADC A", bytes: 1, cycles: "4", desc: "Add Accumulator A and Carry Flag to Accumulator A" },
  { opcode: "90", mnemonic: "SUB B", bytes: 1, cycles: "4", desc: "Subtract Register B from Accumulator A" },
  { opcode: "91", mnemonic: "SUB C", bytes: 1, cycles: "4", desc: "Subtract Register C from Accumulator A" },
  { opcode: "92", mnemonic: "SUB D", bytes: 1, cycles: "4", desc: "Subtract Register D from Accumulator A" },
  { opcode: "93", mnemonic: "SUB E", bytes: 1, cycles: "4", desc: "Subtract Register E from Accumulator A" },
  { opcode: "94", mnemonic: "SUB H", bytes: 1, cycles: "4", desc: "Subtract Register H from Accumulator A" },
  { opcode: "95", mnemonic: "SUB L", bytes: 1, cycles: "4", desc: "Subtract Register L from Accumulator A" },
  { opcode: "96", mnemonic: "SUB M", bytes: 1, cycles: "7", desc: "Subtract memory pointed by HL from Accumulator A" },
  { opcode: "97", mnemonic: "SUB A", bytes: 1, cycles: "4", desc: "Subtract Accumulator A from Accumulator A" },
  { opcode: "98", mnemonic: "SBB B", bytes: 1, cycles: "4", desc: "Subtract Register B and Borrow (CY) from Accumulator A" },
  { opcode: "99", mnemonic: "SBB C", bytes: 1, cycles: "4", desc: "Subtract Register C and Borrow (CY) from Accumulator A" },
  { opcode: "9A", mnemonic: "SBB D", bytes: 1, cycles: "4", desc: "Subtract Register D and Borrow (CY) from Accumulator A" },
  { opcode: "9B", mnemonic: "SBB E", bytes: 1, cycles: "4", desc: "Subtract Register E and Borrow (CY) from Accumulator A" },
  { opcode: "9C", mnemonic: "SBB H", bytes: 1, cycles: "4", desc: "Subtract Register H and Borrow (CY) from Accumulator A" },
  { opcode: "9D", mnemonic: "SBB L", bytes: 1, cycles: "4", desc: "Subtract Register L and Borrow (CY) from Accumulator A" },
  { opcode: "9E", mnemonic: "SBB M", bytes: 1, cycles: "7", desc: "Subtract memory pointed by HL and Borrow (CY) from Accumulator A" },
  { opcode: "9F", mnemonic: "SBB A", bytes: 1, cycles: "4", desc: "Subtract Accumulator A and Borrow (CY) from Accumulator A" },
  { opcode: "A0", mnemonic: "ANA B", bytes: 1, cycles: "4", desc: "Logical AND Register B with Accumulator A" },
  { opcode: "A1", mnemonic: "ANA C", bytes: 1, cycles: "4", desc: "Logical AND Register C with Accumulator A" },
  { opcode: "A2", mnemonic: "ANA D", bytes: 1, cycles: "4", desc: "Logical AND Register D with Accumulator A" },
  { opcode: "A3", mnemonic: "ANA E", bytes: 1, cycles: "4", desc: "Logical AND Register E with Accumulator A" },
  { opcode: "A4", mnemonic: "ANA H", bytes: 1, cycles: "4", desc: "Logical AND Register H with Accumulator A" },
  { opcode: "A5", mnemonic: "ANA L", bytes: 1, cycles: "4", desc: "Logical AND Register L with Accumulator A" },
  { opcode: "A6", mnemonic: "ANA M", bytes: 1, cycles: "7", desc: "Logical AND memory pointed by HL with Accumulator A" },
  { opcode: "A7", mnemonic: "ANA A", bytes: 1, cycles: "4", desc: "Logical AND Accumulator A with Accumulator A" },
  { opcode: "A8", mnemonic: "XRA B", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Register B with Accumulator A" },
  { opcode: "A9", mnemonic: "XRA C", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Register C with Accumulator A" },
  { opcode: "AA", mnemonic: "XRA D", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Register D with Accumulator A" },
  { opcode: "AB", mnemonic: "XRA E", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Register E with Accumulator A" },
  { opcode: "AC", mnemonic: "XRA H", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Register H with Accumulator A" },
  { opcode: "AD", mnemonic: "XRA L", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Register L with Accumulator A" },
  { opcode: "AE", mnemonic: "XRA M", bytes: 1, cycles: "7", desc: "Logical Exclusive OR memory pointed by HL with Accumulator A" },
  { opcode: "AF", mnemonic: "XRA A", bytes: 1, cycles: "4", desc: "Logical Exclusive OR Accumulator A with Accumulator A" },
  { opcode: "B0", mnemonic: "ORA B", bytes: 1, cycles: "4", desc: "Logical OR Register B with Accumulator A" },
  { opcode: "B1", mnemonic: "ORA C", bytes: 1, cycles: "4", desc: "Logical OR Register C with Accumulator A" },
  { opcode: "B2", mnemonic: "ORA D", bytes: 1, cycles: "4", desc: "Logical OR Register D with Accumulator A" },
  { opcode: "B3", mnemonic: "ORA E", bytes: 1, cycles: "4", desc: "Logical OR Register E with Accumulator A" },
  { opcode: "B4", mnemonic: "ORA H", bytes: 1, cycles: "4", desc: "Logical OR Register H with Accumulator A" },
  { opcode: "B5", mnemonic: "ORA L", bytes: 1, cycles: "4", desc: "Logical OR Register L with Accumulator A" },
  { opcode: "B6", mnemonic: "ORA M", bytes: 1, cycles: "7", desc: "Logical OR memory pointed by HL with Accumulator A" },
  { opcode: "B7", mnemonic: "ORA A", bytes: 1, cycles: "4", desc: "Logical OR Accumulator A with Accumulator A" },
  { opcode: "B8", mnemonic: "CMP B", bytes: 1, cycles: "4", desc: "Compare Register B with Accumulator A (sets flags)" },
  { opcode: "B9", mnemonic: "CMP C", bytes: 1, cycles: "4", desc: "Compare Register C with Accumulator A (sets flags)" },
  { opcode: "BA", mnemonic: "CMP D", bytes: 1, cycles: "4", desc: "Compare Register D with Accumulator A (sets flags)" },
  { opcode: "BB", mnemonic: "CMP E", bytes: 1, cycles: "4", desc: "Compare Register E with Accumulator A (sets flags)" },
  { opcode: "BC", mnemonic: "CMP H", bytes: 1, cycles: "4", desc: "Compare Register H with Accumulator A (sets flags)" },
  { opcode: "BD", mnemonic: "CMP L", bytes: 1, cycles: "4", desc: "Compare Register L with Accumulator A (sets flags)" },
  { opcode: "BE", mnemonic: "CMP M", bytes: 1, cycles: "7", desc: "Compare memory pointed by HL with Accumulator A" },
  { opcode: "BF", mnemonic: "CMP A", bytes: 1, cycles: "4", desc: "Compare Accumulator A with Accumulator A (sets flags)" },

  // --- C0H to FFH (Branch, Stack, Immediate Group: 59 valid opcodes) ---
  { opcode: "C0", mnemonic: "RNZ", bytes: 1, cycles: "6/12", desc: "Return if Zero flag is 0 (NZ)" },
  { opcode: "C1", mnemonic: "POP B", bytes: 1, cycles: "10", desc: "Pop Register Pair B-C from top of Stack" },
  { opcode: "C2", mnemonic: "JNZ addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Zero flag is 0 (NZ)" },
  { opcode: "C3", mnemonic: "JMP addr", bytes: 3, cycles: "10", desc: "Unconditional Jump to 16-bit address" },
  { opcode: "C4", mnemonic: "CNZ addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Zero flag is 0 (NZ)" },
  { opcode: "C5", mnemonic: "PUSH B", bytes: 1, cycles: "12", desc: "Push Register Pair B-C onto Stack" },
  { opcode: "C6", mnemonic: "ADI d8", bytes: 2, cycles: "7", desc: "Add immediate 8-bit data to Accumulator A" },
  { opcode: "C7", mnemonic: "RST 0", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0000H" },
  { opcode: "C8", mnemonic: "RZ", bytes: 1, cycles: "6/12", desc: "Return if Zero flag is 1 (Z)" },
  { opcode: "C9", mnemonic: "RET", bytes: 1, cycles: "10", desc: "Unconditional Return from subroutine" },
  { opcode: "CA", mnemonic: "JZ addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Zero flag is 1 (Z)" },
  { opcode: "CC", mnemonic: "CZ addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Zero flag is 1 (Z)" },
  { opcode: "CD", mnemonic: "CALL addr", bytes: 3, cycles: "18", desc: "Unconditional Call to subroutine at 16-bit address" },
  { opcode: "CE", mnemonic: "ACI d8", bytes: 2, cycles: "7", desc: "Add immediate 8-bit data with Carry to Accumulator A" },
  { opcode: "CF", mnemonic: "RST 1", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0008H" },
  { opcode: "D0", mnemonic: "RNC", bytes: 1, cycles: "6/12", desc: "Return if Carry flag is 0 (NC)" },
  { opcode: "D1", mnemonic: "POP D", bytes: 1, cycles: "10", desc: "Pop Register Pair D-E from top of Stack" },
  { opcode: "D2", mnemonic: "JNC addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Carry flag is 0 (NC)" },
  { opcode: "D3", mnemonic: "OUT port", bytes: 2, cycles: "10", desc: "Output contents of Accumulator A to I/O port" },
  { opcode: "D4", mnemonic: "CNC addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Carry flag is 0 (NC)" },
  { opcode: "D5", mnemonic: "PUSH D", bytes: 1, cycles: "12", desc: "Push Register Pair D-E onto Stack" },
  { opcode: "D6", mnemonic: "SUI d8", bytes: 2, cycles: "7", desc: "Subtract immediate 8-bit data from Accumulator A" },
  { opcode: "D7", mnemonic: "RST 2", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0010H" },
  { opcode: "D8", mnemonic: "RC", bytes: 1, cycles: "6/12", desc: "Return if Carry flag is 1 (C)" },
  { opcode: "DA", mnemonic: "JC addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Carry flag is 1 (C)" },
  { opcode: "DB", mnemonic: "IN port", bytes: 2, cycles: "10", desc: "Input 8-bit data from I/O port to Accumulator A" },
  { opcode: "DC", mnemonic: "CC addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Carry flag is 1 (C)" },
  { opcode: "DE", mnemonic: "SBI d8", bytes: 2, cycles: "7", desc: "Subtract immediate 8-bit data with Borrow from Accumulator A" },
  { opcode: "DF", mnemonic: "RST 3", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0018H" },
  { opcode: "E0", mnemonic: "RPO", bytes: 1, cycles: "6/12", desc: "Return if Parity flag is 0 (PO - Odd)" },
  { opcode: "E1", mnemonic: "POP H", bytes: 1, cycles: "10", desc: "Pop Register Pair H-L from top of Stack" },
  { opcode: "E2", mnemonic: "JPO addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Parity flag is 0 (PO - Odd)" },
  { opcode: "E3", mnemonic: "XTHL", bytes: 1, cycles: "16", desc: "Exchange top of stack with Register Pair H-L" },
  { opcode: "E4", mnemonic: "CPO addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Parity flag is 0 (PO - Odd)" },
  { opcode: "E5", mnemonic: "PUSH H", bytes: 1, cycles: "12", desc: "Push Register Pair H-L onto Stack" },
  { opcode: "E6", mnemonic: "ANI d8", bytes: 2, cycles: "7", desc: "Logical AND immediate 8-bit data with Accumulator A" },
  { opcode: "E7", mnemonic: "RST 4", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0020H" },
  { opcode: "E8", mnemonic: "RPE", bytes: 1, cycles: "6/12", desc: "Return if Parity flag is 1 (PE - Even)" },
  { opcode: "E9", mnemonic: "PCHL", bytes: 1, cycles: "6", desc: "Copy Register Pair H-L to Program Counter PC (Jump to HL)" },
  { opcode: "EA", mnemonic: "JPE addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Parity flag is 1 (PE - Even)" },
  { opcode: "EB", mnemonic: "XCHG", bytes: 1, cycles: "4", desc: "Exchange contents of Register Pair H-L with D-E" },
  { opcode: "EC", mnemonic: "CPE addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Parity flag is 1 (PE - Even)" },
  { opcode: "EE", mnemonic: "XRI d8", bytes: 2, cycles: "7", desc: "Logical Exclusive OR immediate 8-bit data with Accumulator A" },
  { opcode: "EF", mnemonic: "RST 5", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0028H" },
  { opcode: "F0", mnemonic: "RP", bytes: 1, cycles: "6/12", desc: "Return if Sign flag is 0 (P - Positive)" },
  { opcode: "F1", mnemonic: "POP PSW", bytes: 1, cycles: "10", desc: "Pop Accumulator A and Flags F (PSW) from top of Stack" },
  { opcode: "F2", mnemonic: "JP addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Sign flag is 0 (P - Positive)" },
  { opcode: "F3", mnemonic: "DI", bytes: 1, cycles: "4", desc: "Disable Interrupts (resets interrupt enable flip-flop)" },
  { opcode: "F4", mnemonic: "CP addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Sign flag is 0 (P - Positive)" },
  { opcode: "F5", mnemonic: "PUSH PSW", bytes: 1, cycles: "12", desc: "Push Accumulator A and Flags F (PSW) onto Stack" },
  { opcode: "F6", mnemonic: "ORI d8", bytes: 2, cycles: "7", desc: "Logical OR immediate 8-bit data with Accumulator A" },
  { opcode: "F7", mnemonic: "RST 6", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0030H" },
  { opcode: "F8", mnemonic: "RM", bytes: 1, cycles: "6/12", desc: "Return if Sign flag is 1 (M - Minus/Negative)" },
  { opcode: "F9", mnemonic: "SPHL", bytes: 1, cycles: "6", desc: "Copy Register Pair H-L to Stack Pointer SP" },
  { opcode: "FA", mnemonic: "JM addr", bytes: 3, cycles: "10", desc: "Jump to 16-bit address if Sign flag is 1 (M - Minus/Negative)" },
  { opcode: "FB", mnemonic: "EI", bytes: 1, cycles: "4", desc: "Enable Interrupts (sets interrupt enable flip-flop)" },
  { opcode: "FC", mnemonic: "CM addr", bytes: 3, cycles: "9/18", desc: "Call 16-bit address if Sign flag is 1 (M - Minus/Negative)" },
  { opcode: "FE", mnemonic: "CPI d8", bytes: 2, cycles: "7", desc: "Compare immediate 8-bit data with Accumulator A (sets flags)" },
  { opcode: "FF", mnemonic: "RST 7", bytes: 1, cycles: "12", desc: "Software Restart / Call to memory location 0038H" }
];
